Leave one specific number in array as is and make everything else 0

In [18]:
import numpy as np

In [19]:
one = np.full((2,2), 1)
two = np.full((2,2), 2)
three = np.full((2,2), 3)

In [20]:
a = np.stack([one,two,three])

In [21]:
a

array([[[1, 1],
        [1, 1]],

       [[2, 2],
        [2, 2]],

       [[3, 3],
        [3, 3]]])

Human: 11,12
Vehicle: 13,14,15,16,17,18,-1

for one element

In [22]:
(a==1).astype(np.uint8)

array([[[1, 1],
        [1, 1]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=uint8)

for multiple elements

In [17]:
np.isin(a, [1,2]).astype(int)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[0, 0],
        [0, 0]]])