In [1]:
import numpy as np
import torch

In [2]:
ones = np.full((3,4,4), 255)
ones.shape

(3, 4, 4)

In [3]:
zeros = np.zeros((3,4,4))
zeros.shape

(3, 4, 4)

In [4]:
ones

array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]]])

In [5]:
a = np.stack([ones, zeros])

In [6]:
a.shape

(2, 3, 4, 4)

In [7]:
a = torch.from_numpy(a).cuda()

In [8]:
t = torch.div(a, 255.0)

In [10]:
a

tensor([[[[255., 255., 255., 255.],
          [255., 255., 255., 255.],
          [255., 255., 255., 255.],
          [255., 255., 255., 255.]],

         [[255., 255., 255., 255.],
          [255., 255., 255., 255.],
          [255., 255., 255., 255.],
          [255., 255., 255., 255.]],

         [[255., 255., 255., 255.],
          [255., 255., 255., 255.],
          [255., 255., 255., 255.],
          [255., 255., 255., 255.]]],


        [[[  0.,   0.,   0.,   0.],
          [  0.,   0.,   0.,   0.],
          [  0.,   0.,   0.,   0.],
          [  0.,   0.,   0.,   0.]],

         [[  0.,   0.,   0.,   0.],
          [  0.,   0.,   0.,   0.],
          [  0.,   0.,   0.,   0.],
          [  0.,   0.,   0.,   0.]],

         [[  0.,   0.,   0.,   0.],
          [  0.,   0.,   0.,   0.],
          [  0.,   0.,   0.,   0.],
          [  0.,   0.,   0.,   0.]]]], device='cuda:0', dtype=torch.float64)

In [11]:
mean = (0.485, 0.456, 0.406)
std = (0.229, 0.224, 0.225)

In [12]:
mean = torch.as_tensor(mean, dtype=torch.float)[None, :, None, None].cuda()
std = torch.as_tensor(std, dtype=torch.float)[None, :, None, None].cuda()

In [13]:
mean.shape

torch.Size([1, 3, 1, 1])

In [15]:
a.shape

torch.Size([2, 3, 4, 4])

In [16]:
a.sub_(mean).div_(std)

tensor([[[[1111.4192, 1111.4192, 1111.4192, 1111.4192],
          [1111.4192, 1111.4192, 1111.4192, 1111.4192],
          [1111.4192, 1111.4192, 1111.4192, 1111.4192],
          [1111.4192, 1111.4192, 1111.4192, 1111.4192]],

         [[1136.3571, 1136.3571, 1136.3571, 1136.3571],
          [1136.3571, 1136.3571, 1136.3571, 1136.3571],
          [1136.3571, 1136.3571, 1136.3571, 1136.3571],
          [1136.3571, 1136.3571, 1136.3571, 1136.3571]],

         [[1131.5289, 1131.5289, 1131.5289, 1131.5289],
          [1131.5289, 1131.5289, 1131.5289, 1131.5289],
          [1131.5289, 1131.5289, 1131.5289, 1131.5289],
          [1131.5289, 1131.5289, 1131.5289, 1131.5289]]],


        [[[  -2.1179,   -2.1179,   -2.1179,   -2.1179],
          [  -2.1179,   -2.1179,   -2.1179,   -2.1179],
          [  -2.1179,   -2.1179,   -2.1179,   -2.1179],
          [  -2.1179,   -2.1179,   -2.1179,   -2.1179]],

         [[  -2.0357,   -2.0357,   -2.0357,   -2.0357],
          [  -2.0357,   -2.0357,   -2.