In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

## MSE

In [3]:
x = torch.randn(4, requires_grad=True); x

tensor([ 0.2095,  0.5321,  0.2335, -1.2680], requires_grad=True)

In [4]:
y = torch.randn(4, requires_grad=True); y

tensor([ 0.1639,  0.0345, -1.7227,  1.6151], requires_grad=True)

In [5]:
F.mse_loss(x,y)

tensor(3.0973, grad_fn=<MeanBackward0>)

In [10]:
l = (x-y).pow(2).mean(); l

tensor(3.0973, grad_fn=<MeanBackward0>)

In [11]:
l.backward()

In [17]:
(x[0]-y[0])*1/2

tensor(0.0228, grad_fn=<DivBackward0>)

In [14]:
x.grad

tensor([ 0.0228,  0.2488,  0.9781, -1.4416])

## BCE

In [87]:
y_hat = torch.rand(4, requires_grad=True); y_hat

tensor([0.8731, 0.0865, 0.1515, 0.1494], requires_grad=True)

In [88]:
y_hat.shape

torch.Size([4])

In [105]:
y = torch.Tensor([1,0,0,0]); y

tensor([1., 0., 0., 0.])

In [106]:
y.shape

torch.Size([4])

In [107]:
F.binary_cross_entropy(torch.sigmoid(y_hat), y)

tensor(0.8961, grad_fn=<BinaryCrossEntropyBackward>)

In [108]:
y_hat = torch.sigmoid(y_hat); y_hat

tensor([0.6614, 0.6519, 0.6528, 0.6528], grad_fn=<SigmoidBackward>)

In [109]:
l = (y * torch.log(y_hat)) + ((1-y) * torch.log(1-y_hat))

In [110]:
l.sum() * -(1/4)

tensor(0.8961, grad_fn=<MulBackward0>)

## CE

In [196]:
y_hat = torch.rand(1,4, requires_grad=True); y_hat

tensor([[0.9894, 0.7660, 0.0225, 0.4305]], requires_grad=True)

In [197]:
y = y_hat.argmax(); y

tensor(0)

In [198]:
F.cross_entropy(y_hat, y[None])

tensor(1.0123, grad_fn=<NllLossBackward>)

In [199]:
y_hat_ce = F.softmax(y_hat, dim=1); y_hat

tensor([[0.9894, 0.7660, 0.0225, 0.4305]], requires_grad=True)

In [200]:
-torch.log(y_hat_ce[0][y])

tensor(1.0123, grad_fn=<NegBackward>)

### CE = Log Softmax + NLL

In [194]:
t = F.log_softmax(y_hat, dim=1); t

tensor([[-1.3099, -1.3173, -1.2938, -1.6710]], grad_fn=<LogSoftmaxBackward>)

In [195]:
F.nll_loss(t, y[None])

tensor(1.2938, grad_fn=<NllLossBackward>)