In [49]:
import torch
import torch.nn as nn

## MaxPool

In [50]:
x = torch.randn(1, 3, 3, requires_grad=True)

In [51]:
x

tensor([[[ 0.4158, -1.1861, -0.4135],
         [-0.6704, -0.7182, -0.2774],
         [ 0.3971, -0.1424, -1.3894]]], requires_grad=True)

In [52]:
mp = nn.MaxPool2d(3)

In [53]:
y = mp(x); y

tensor([[[0.4158]]], grad_fn=<MaxPool2DWithIndicesBackward>)

In [54]:
y.backward()

In [55]:
x.grad

tensor([[[1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

## AveragePool

In [57]:
x = torch.randn(1, 3, 3, requires_grad=True); x

tensor([[[ 0.4742,  0.3464,  0.1794],
         [ 0.7919,  0.8854,  1.0897],
         [ 0.9560, -1.2428,  0.6548]]], requires_grad=True)

In [58]:
ap = nn.AvgPool2d(3)

In [59]:
y = ap(x); y

tensor([[[0.4594]]], grad_fn=<AvgPool2DBackward>)

In [60]:
y.backward()

In [62]:
x.grad

tensor([[[0.1111, 0.1111, 0.1111],
         [0.1111, 0.1111, 0.1111],
         [0.1111, 0.1111, 0.1111]]])

## AdaptiveMaxPool

In [79]:
x = torch.randn(1, 3, 3, requires_grad=True); x

tensor([[[-1.8115,  0.7486, -2.1681],
         [-0.1520, -1.0668, -0.1327],
         [-1.3503,  0.1748,  0.3461]]], requires_grad=True)

In [80]:
amp = nn.AdaptiveMaxPool2d((1,1))

In [81]:
y = amp(x); y

tensor([[[0.7486]]], grad_fn=<AdaptiveMaxPool2DBackward>)

In [82]:
y.backward()

In [83]:
x.grad

tensor([[[0., 1., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [84]:
x.argmax()

tensor(1)