In [6]:
import numpy as np
import torch
from torchvision import transforms as tfms

In [247]:
to_tensor = tfms.Compose([tfms.ToTensor(), tfms.Normalize(0.5, 0.5)])

In [260]:
s = 255

In [261]:
x = np.ones((10,10), dtype=np.uint8)*s; 
#x = torch.ones(1,10,10)*s; 
x

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], dtype=uint8)

In [262]:
y = to_tensor(x); y

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [263]:
((x/255)-0.5)/0.5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [264]:
((y*0.5)+0.5)*255

tensor([[[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
         [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
         [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
         [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
         [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
         [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
         [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
         [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
         [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
         [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]]])